apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: hmzih8kiu-go 
  janus-idp.io/tekton: hmzih8kiu-go
  backstage.io/kubernetes-id: hmzih8kiu-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hmzih8kiu-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml